services:
  - type: web
    name: arboviroses-backend-final
    env: python
    plan: free
    region: oregon
    autoDeploy: true

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 2 -t 120 -b 0.0.0.0:$PORT src.main:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

    healthCheckPath: /docs
