services:
  - type: web
    name: arboviroses-platform
    env: python
    branch: master
    buildCommand: |
      pip install -r backend/requirements.txt
      export NODE_VERSION=20.16.0
      curl -fsSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" -o /tmp/node.tar.xz
      mkdir -p "$HOME/node"
      tar -xJf /tmp/node.tar.xz -C "$HOME/node" --strip-components=1
      export PATH="$HOME/node/bin:$PATH"
      cd frontend && (npm ci --no-audit --no-fund || npm install --no-audit --no-fund) && npm run build
      rm -rf backend/static/dashboard && mkdir -p backend/static/dashboard
      cp -r frontend/dist/* backend/static/dashboard/
    startCommand: |
      python backend/scripts/build_database.py || true
      uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
