name: CI and optional Render deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          cd backend
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
      - name: Run backend lint/test (placeholder)
        run: |
          echo "Add unit tests here"

  deploy-to-render:
    if: env.RENDER_API_KEY != '' && env.RENDER_SERVICE_ID != ''
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Render Deploy via API
        run: |
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys"                 -H "Authorization: Bearer ${RENDER_API_KEY}"                 -H "Accept: application/json"                 -H "Content-Type: application/json"                 -d '{"clearCache":true}'
